feat(auth-cron): implemented
MapColonies/opa-la pull request #13
Opened 2023-05-04 08:14 UTC by CptSchnitz

2023-05-04 10:05 UTC, syncush requested changes
1. run prettier

2023-05-08 07:56 UTC, syncush approved these changes

2023-05-18 21:10 UTC, syncush requested changes

2023-05-18 21:10 UTC, syncush commented on packages/auth-cron/helm/templates/deployment.yaml
> +          #     port: {{ .Values.env.targetPort }}
?

2023-05-24 08:37 UTC, syncush requested changes

2023-05-24 10:34 UTC, CptSchnitz commented on packages/auth-cron/src/index.ts
> +  // });
im stupid

2023-05-24 10:42 UTC, syncush approved these changes

2023-05-24 11:16 UTC, merged