feat: integrate with mapcolonies config manager
MapColonies/opa-la pull request #43
Opened 2024-10-07 15:03 UTC by ronenkapelian

Integrate service with config managment stack including dedicated schema for opa-la

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2024-11-14 08:31 UTC, ronenkapelian commented on packages/auth-bundler/package.json
> +    "@map-colonies/schemas": "file:/home/ronenk1/dev/infra/schemas",
good idea

2024-11-14 08:52 UTC, ronenkapelian commented on packages/auth-bundler/tests/opa.spec.ts
> +      jest.spyOn(execa, 'execa').mockResolvedValue({ failed: false } as Awaited<ReturnType<(typeof execa)['execa']>>);
good comment :) changed.

2024-11-14 09:04 UTC, ronenkapelian commented on packages/auth-core/package.json
> +    "@map-colonies/config": "^1.1.0"
done

2024-11-14 09:11 UTC, ronenkapelian commented on packages/auth-core/src/config.ts
> +  });
done

2024-11-14 11:34 UTC, ronenkapelian commented on packages/auth-core/src/db/types/interfaces.ts
>  } & PostgresConnectionOptions;
changed, now it using part of schema original entity

2024-11-14 11:36 UTC, ronenkapelian commented on packages/auth-core/src/instrumentation.mts
![image](https://github.com/user-attachments/assets/f3f989c2-5ae5-4aef-a045-bafb5379667c)

its already include migrations script, so on such use case it is needed

2024-11-14 11:49 UTC, ronenkapelian commented on packages/auth-cron/src/config.ts
> +    offlineMode: offlineMode,
done

2024-11-17 17:00 UTC, CptSchnitz commented on packages/auth-core/src/instrumentation.mts
reminding you, it should not be part of src

2024-11-17 17:15 UTC, CptSchnitz requested changes
you can also release a new version of schemas and add it to the PR

2024-11-17 17:15 UTC, CptSchnitz commented on packages/auth-cron/src/config.ts
>      configServerUrl: 'http://localhost:8080',
can also be removed

2024-11-18 07:42 UTC, ronenkapelian commented on packages/auth-bundler/config/custom-environment-variables.json
it seems you are right, there is no need for this module. i will delete

2024-11-18 07:42 UTC, ronenkapelian commented on packages/auth-cron/src/config.ts
>      configServerUrl: 'http://localhost:8080',
removed

2024-11-18 11:41 UTC, ronenkapelian commented on packages/auth-core/src/instrumentation.mts
removed

2024-11-20 08:02 UTC, ronenkapelian commented on packages/auth-cron/tests/validators.spec.ts
> -    });
you name it

2024-11-20 11:52 UTC, ronenkapelian commented on packages/auth-bundler/package.json
> +    "@map-colonies/schemas": "file:/home/ronenk1/dev/infra/schemas",
updated to v1.1.0 of schemas

2024-11-25 07:01 UTC, netanelC requested changes
Good Job!

2024-11-25 12:01 UTC, ronenkapelian commented on packages/auth-bundler/tests/configurations/jest.globalSetup.ts
> +  // eslint-disable-next-line @typescript-eslint/no-magic-numbers
removed

2024-11-26 07:15 UTC, ronenkapelian commented on packages/auth-manager/tests/integration/client/client.spec.ts
> +  });
done

2024-11-26 07:16 UTC, ronenkapelian commented on packages/auth-manager/tests/integration/domain/domain.spec.ts
> +  });
done

2024-11-26 07:18 UTC, ronenkapelian commented on packages/auth-manager/config/default.json
> +    "shared": {}
![image](https://github.com/user-attachments/assets/665f93be-76b5-4fbf-b739-acb19d5525f7)

it is part of the boilerplate schema: 
https://github.com/MapColonies/schemas/blob/master/schemas/common/boilerplate/v1.schema.json

2024-11-26 07:27 UTC, ronenkapelian commented on packages/auth-bundler/tests/tsconfig.json
> +    "include": ["."],
yes, it is for auto-completion of types inside this tests

2024-11-28 20:50 UTC, netanelC commented on packages/auth-manager/config/default.json
> +    "shared": {}
It is not required, if you keep it as an empty object, don't put it

2024-11-28 20:54 UTC, netanelC reviewed
Fix the issues with the config package as we saw today and then this will be considered as approved to me. Wait for Ofer to final approve and merge it

2024-12-02 07:15 UTC, CptSchnitz approved these changes

2024-12-05 08:26 UTC, merged