feat(auth-manager): implemented connection resource including tests
MapColonies/opa-la pull request #7
Opened 2023-04-05 09:33 UTC by CptSchnitz

2023-04-08 19:59 UTC, syncush requested changes

2023-04-08 19:59 UTC, syncush commented on packages/auth-manager/src/connection/DAL/connectionRepository.ts
> +
maybe external function?

2023-04-08 19:59 UTC, syncush commented on packages/auth-manager/src/domain/DAL/domainRepository.ts
> +        SELECT i.name FROM unnest($1::text[]) i(name) LEFT JOIN auth_manager.domain d ON i.name = d.name WHERE d.name is NULL`,
is it postgres only sql?

2023-04-08 19:59 UTC, syncush commented on packages/auth-manager/tests/integration/domain/domain.spec.ts
> +        expect(res.body).toEqual(expect.arrayContaining([{ name: 'avi' }, { name: 'iva' }]));
iva is avi's wife

2023-04-09 04:26 UTC, CptSchnitz commented on packages/auth-manager/src/domain/DAL/domainRepository.ts
> +        SELECT i.name FROM unnest($1::text[]) i(name) LEFT JOIN auth_manager.domain d ON i.name = d.name WHERE d.name is NULL`,
yes

2023-04-09 04:58 UTC, CptSchnitz commented on packages/auth-manager/src/connection/DAL/connectionRepository.ts
> +
extracted

2023-04-09 11:27 UTC, syncush commented on packages/auth-manager/src/domain/DAL/domainRepository.ts
> +        SELECT i.name FROM unnest($1::text[]) i(name) LEFT JOIN auth_manager.domain d ON i.name = d.name WHERE d.name is NULL`,
I would add that to the comment

2023-04-09 11:28 UTC, syncush approved these changes

2023-04-09 11:28 UTC, syncush commented
I approved with a small comment for the sql

2023-04-09 14:08 UTC, merged