feat(auth-core,auth-manager): created core package
MapColonies/opa-la pull request #9
Opened 2023-04-13 09:39 UTC by CptSchnitz

the package contains both db settings and migrations.

2023-04-13 11:16 UTC, syncush requested changes

2023-04-13 13:04 UTC, CptSchnitz commented on packages/auth-core/dataSource.ts
> +  // migrations,
removed

2023-04-13 13:05 UTC, CptSchnitz commented on packages/auth-core/src/db/migrations/index.ts
> +import { addDomain1679474009991 } from './1679474009991-addDomain';
changed

2023-04-13 13:05 UTC, CptSchnitz commented on packages/auth-manager/src/bundle/controllers/bundleController.ts
> +import { IBundle } from 'auth-core';
planned on handling it later, but changed it now

2023-04-16 07:23 UTC, syncush approved these changes

2023-04-16 07:42 UTC, merged